blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://protspace.app/docs/
    about: Please check our documentation before creating an issue
  - name: ðŸ’¬ Discussion
    url: ../discussions
    about: Start a discussion for general questions or ideas
  - name: ðŸ“œ Code of Conduct
    url: ../blob/main/CODE_OF_CONDUCT.md
    about: Please read our Code of Conduct before contributing
